services:
  db:
    image: postgres:latest
    container_name: crawlerx-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crawlerx
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: crawlerx-app
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/crawlerx?sslmode=disable

  redis:
    image: redis:latest
    container_name: crawlerx-redis
    ports:
      - "6379:6379"

volumes:
  pgdata: