services:
  # Backend API service
  - type: web
    name: crawlerx
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crawlerx-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: crawlerx-redis
          property: connectionString
      - key: PORT
        value: 8080
      - key: LOG_LEVEL
        value: info

  # Redis service
  - type: redis
    name: crawlerx-redis
    plan: free
    ipAllowList: []

# Database
databases:
  - name: crawlerx-db
    plan: free
    databaseName: crawlerx
