services:
  # Backend API service
  - type: web
    name: crawlerx
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crawlerx-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: crawlerx-redis
          property: connectionString
      - fromGroup: crawlerx-env

# Database
databases:
  - name: crawlerx-db
    plan: free
    databaseName: crawlerx
    user: postgres

# Redis
redis:
  - name: crawlerx-redis
    plan: free
    ipAllowList: []

# Environment variable groups
envGroups:
  - name: crawlerx-env
    envVars:
      - key: PORT
        value: 8080
      - key: LOG_LEVEL
        value: info
